# Generated by Django 3.0 on 2022-09-22 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodwasteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetails',
            name='requested_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
