# Generated by Django 3.0 on 2022-09-22 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodwasteapp', '0002_auto_20220921_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddetails',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='fooddetails',
            name='requested_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
