# Generated by Django 3.0 on 2022-09-28 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodwasteapp', '0003_auto_20220922_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddetails',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=255, null=True),
        ),
    ]
